# Generated by Django 4.1 on 2022-09-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=30)),
                ("email_id", models.EmailField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                ("contact_number", models.IntegerField(max_length=10)),
                ("role", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
            ],
        ),
    ]
