# Generated by Django 4.1.1 on 2022-09-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contact_number",
            field=models.IntegerField(),
        ),
    ]
