# Generated by Django 4.1.1 on 2022-09-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_customer_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contact_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Others"),
                    ("P", "Preffer Not To Respond"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="role",
            field=models.CharField(
                choices=[("A", "admin"), ("U", "user")], default="U", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user_name",
            field=models.CharField(max_length=10),
        ),
    ]
