# Generated by Django 4.1.1 on 2022-09-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_customer_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("A", "admin"), ("U", "user")],
                default="U",
                max_length=1,
            ),
        ),
    ]
